bot:
  token: 5742413451:AAFpk66EOBf3Oit6x4Wf1Qfx7U7oBwURFvA
  name: '@oauthgooglebot'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pdfbot
    username: postgres
    password: husanboy2002
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
server:
  port: 8081